"""PDF report generator for evaluation results.

Creates a professional EU AI Act audit-style PDF report.
"""

import json
from pathlib import Path

from fpdf import FPDF
from sqlalchemy.orm import Session

from fairly.db.crud_evaluations import get_evaluation, list_inferences, list_metrics

# Corporate color palette
_PRIMARY = (99, 102, 241)     # Indigo-500
_DARK = (30, 30, 46)          # Near-black
_LIGHT_BG = (241, 243, 249)   # Very light indigo
_WHITE = (255, 255, 255)
_GRAY = (107, 114, 128)
_GREEN = (16, 185, 129)
_RED = (239, 68, 68)
_AMBER = (245, 158, 11)


def _sanitize(text: str) -> str:
    """Replace Unicode characters unsupported by fpdf2 Helvetica with ASCII."""
    replacements = {
        "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"',
        "\u2013": "-", "\u2014": "--",
        "\u2026": "...",
        "\u00a0": " ",
        "\u2022": "*",
    }
    for char, repl in replacements.items():
        text = text.replace(char, repl)
    return text.encode("latin-1", errors="replace").decode("latin-1")


class _FairlyPDF(FPDF):
    """Custom FPDF with header/footer branding."""

    def header(self):
        if self.page_no() == 1:
            return  # Cover page has its own header
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*_GRAY)
        self.cell(0, 8, "fairly - Bias Evaluation Report", align="L")
        self.cell(0, 8, f"Page {self.page_no()}", align="R", ln=True)
        self.set_draw_color(*_PRIMARY)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*_GRAY)
        self.cell(0, 10, "Generated by fairly | EU AI Act Compliance Toolkit", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 15)
        self.set_text_color(*_DARK)
        self.cell(0, 10, _sanitize(title), ln=True)
        self.set_draw_color(*_PRIMARY)
        self.set_line_width(0.8)
        self.line(10, self.get_y(), 80, self.get_y())
        self.ln(4)

    def sub_title(self, title: str):
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*_DARK)
        self.multi_cell(0, 6, _sanitize(title))
        self.ln(1)

    def color_badge(self, text: str, bg: tuple, fg: tuple = _WHITE):
        """Draw a small colored badge."""
        w = self.get_string_width(text) + 6
        x, y = self.get_x(), self.get_y()
        self.set_fill_color(*bg)
        self.rect(x, y, w, 5, "F")
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*fg)
        self.set_xy(x, y)
        self.cell(w, 5, text, align="C")
        self.set_xy(x + w + 2, y)


def generate_pdf(db: Session, evaluation_id: int, output_path: str | Path) -> Path:
    """Generate a professional PDF report for a completed evaluation."""
    from collections import Counter, defaultdict

    from fairly.db.models import ColumnMapping, Dimension
    from fairly.eval.runner import classify_response

    evaluation = get_evaluation(db, evaluation_id)
    if evaluation is None:
        raise ValueError(f"Evaluation {evaluation_id} not found")

    inferences = list_inferences(db, evaluation_id)

    pdf = _FairlyPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── Cover Page ────────────────────────────────────────────────────────
    pdf.add_page()
    # Indigo banner
    pdf.set_fill_color(*_PRIMARY)
    pdf.rect(0, 0, 210, 100, "F")

    # Logo or fallback text
    logo_path = Path(__file__).resolve().parent.parent.parent.parent / "logo.png"
    if logo_path.exists():
        pdf.image(str(logo_path), x=65, y=15, w=80)
    else:
        pdf.set_font("Helvetica", "B", 36)
        pdf.set_text_color(*_WHITE)
        pdf.set_y(25)
        pdf.cell(0, 15, "fairly", align="C", ln=True)
    pdf.set_text_color(*_WHITE)
    pdf.set_y(65)
    pdf.set_font("Helvetica", "", 14)
    pdf.cell(0, 8, "Bias Evaluation Report", align="C", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 8, "EU AI Act Compliance Audit", align="C", ln=True)

    # Config table below banner
    pdf.set_y(110)
    pdf.set_text_color(*_DARK)

    config_data = [
        ("Evaluation ID", str(evaluation.evaluation_id)),
        ("Model", _sanitize(evaluation.model.name)),
        ("Dataset", _sanitize(evaluation.dataset.name)),
        ("Domain", _sanitize(evaluation.domain.name)),
        ("Images Sampled", str(evaluation.num_images)),
        ("Resolution", evaluation.images_resolution),
        ("Status", evaluation.status.upper()),
    ]

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "Evaluation Configuration", ln=True)
    pdf.ln(2)

    for label, value in config_data:
        pdf.set_fill_color(*_LIGHT_BG)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*_GRAY)
        pdf.cell(60, 8, label, border=0, fill=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*_DARK)
        pdf.cell(0, 8, value, border=0, ln=True)

    # ── Response Summary ──────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Response Summary")

    response_counts = Counter(
        (inf.classified_response or classify_response(inf.response))
        for inf in inferences
    )
    total = len(inferences)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*_DARK)
    pdf.cell(0, 7, f"Total inferences: {total}", ln=True)
    pdf.ln(3)

    # Summary table with colored rows
    pdf.set_fill_color(*_PRIMARY)
    pdf.set_text_color(*_WHITE)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(80, 7, "  Response Category", fill=True, border=0)
    pdf.cell(30, 7, "Count", fill=True, border=0, align="C")
    pdf.cell(30, 7, "Percentage", fill=True, border=0, align="C", ln=True)

    pdf.set_text_color(*_DARK)
    alt = False
    for category, count in response_counts.most_common():
        pct = round(count / total * 100, 1) if total else 0
        if alt:
            pdf.set_fill_color(*_LIGHT_BG)
        else:
            pdf.set_fill_color(*_WHITE)
        alt = not alt

        # Color-code the category
        if category == "Refused":
            color = _GRAY
        elif category == "No Response":
            color = _RED
        else:
            color = _GREEN

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*color)
        pdf.cell(80, 7, f"  {_sanitize(category)}", fill=True, border=0)
        pdf.set_text_color(*_DARK)
        pdf.cell(30, 7, str(count), fill=True, border=0, align="C")
        pdf.cell(30, 7, f"{pct}%", fill=True, border=0, align="C", ln=True)

    pdf.ln(6)

    # ── Distribution Analysis per Dimension ───────────────────────────────
    mappings = (
        db.query(ColumnMapping)
        .filter(ColumnMapping.dataset_id == evaluation.dataset_id)
        .all()
    )

    by_prompt: dict[int, list] = defaultdict(list)
    for inf in inferences:
        by_prompt[inf.prompt_id].append(inf)

    # CSV fallback for old images without metadata_json
    csv_lookup: dict[str, dict] = {}
    needs_csv = any(
        not inf.image or not inf.image.metadata_json or inf.image.metadata_json in ("{}", "")
        for inf in inferences
    )
    if needs_csv and evaluation.dataset.csv_route:
        try:
            import pandas as pd
            df = pd.read_csv(evaluation.dataset.csv_route)
            img_col = evaluation.dataset.image_column or df.columns[0]
            for _, row in df.iterrows():
                key = str(row[img_col])
                csv_lookup[key] = {str(c): str(v) for c, v in row.items()}
        except Exception:
            pass

    for mapping in mappings:
        dim = db.query(Dimension).filter(Dimension.dimension_id == mapping.dimension_id).first()
        dim_name = dim.name if dim else mapping.name
        csv_col = mapping.name

        pdf.add_page()
        pdf.section_title(f"Analysis by: {dim_name}")

        for prompt_id, items in sorted(by_prompt.items()):
            prompt_text = items[0].prompt.text if items[0].prompt else f"Prompt #{prompt_id}"
            pdf.sub_title(f"Prompt #{prompt_id}: {prompt_text[:100]}")

            cross: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
            for inf in items:
                metadata = {}
                if inf.image and getattr(inf.image, "metadata_json", None):
                    try:
                        metadata = json.loads(inf.image.metadata_json)
                    except Exception:
                        pass
                if not metadata and inf.image and csv_lookup:
                    img_route = inf.image.img_route or ""
                    metadata = csv_lookup.get(img_route, {})
                    if not metadata:
                        from pathlib import PurePosixPath
                        fname = PurePosixPath(img_route).name
                        for csv_key, csv_row in csv_lookup.items():
                            if str(csv_key).endswith(fname) or fname in str(csv_key):
                                metadata = csv_row
                                break

                dim_val = str(metadata.get(csv_col, "Unknown"))
                classified = inf.classified_response or classify_response(inf.response)
                cross[dim_val][classified] += 1

            all_responses = sorted({r for counts in cross.values() for r in counts})

            if not all_responses:
                pdf.set_font("Helvetica", "I", 9)
                pdf.set_text_color(*_GRAY)
                pdf.cell(0, 6, "  No data", ln=True)
                pdf.ln(3)
                continue

            # Table header
            col_w = min(25, int(140 / max(len(all_responses), 1)))
            first_col = 190 - col_w * len(all_responses)
            first_col = max(first_col, 40)

            pdf.set_fill_color(*_PRIMARY)
            pdf.set_text_color(*_WHITE)
            pdf.set_font("Helvetica", "B", 8)
            pdf.cell(first_col, 6, f"  {_sanitize(dim_name)}", fill=True, border=0)
            for r in all_responses:
                pdf.cell(col_w, 6, _sanitize(r[:12]), fill=True, border=0, align="C")
            pdf.ln()

            alt = False
            pdf.set_text_color(*_DARK)
            for dim_val in sorted(cross.keys()):
                if alt:
                    pdf.set_fill_color(*_LIGHT_BG)
                else:
                    pdf.set_fill_color(*_WHITE)
                alt = not alt
                pdf.set_font("Helvetica", "", 8)
                pdf.cell(first_col, 6, f"  {_sanitize(dim_val[:20])}", fill=True, border=0)
                for r in all_responses:
                    pdf.cell(col_w, 6, str(cross[dim_val].get(r, 0)), fill=True, border=0, align="C")
                pdf.ln()

            pdf.ln(4)

    # ── Inference Detail ──────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Inference Detail (by Prompt)")

    for prompt_id, items in sorted(by_prompt.items()):
        prompt_text = items[0].prompt.text if items[0].prompt else f"Prompt #{prompt_id}"
        pdf.sub_title(f"Prompt #{prompt_id}: {prompt_text[:120]}")

        # Table header
        pdf.set_fill_color(*_PRIMARY)
        pdf.set_text_color(*_WHITE)
        pdf.set_font("Helvetica", "B", 7)
        pdf.cell(22, 6, "  Audit", fill=True, border=0)
        pdf.cell(30, 6, "Classification", fill=True, border=0)
        pdf.cell(0, 6, "Model Response", fill=True, border=0, ln=True)

        alt = False
        for inf in items[:10]:
            classified = inf.classified_response or classify_response(inf.response)
            status_tag = inf.audit_status.upper()

            if alt:
                pdf.set_fill_color(*_LIGHT_BG)
            else:
                pdf.set_fill_color(*_WHITE)
            alt = not alt

            # Status column with color
            if status_tag == "FLAG":
                pdf.set_text_color(*_RED)
            elif status_tag == "PASS":
                pdf.set_text_color(*_GREEN)
            else:
                pdf.set_text_color(*_GRAY)
            pdf.set_font("Helvetica", "B", 7)
            pdf.cell(22, 5, f"  {status_tag}", fill=True, border=0)

            # Classification column
            pdf.set_text_color(*_DARK)
            pdf.set_font("Helvetica", "", 7)
            pdf.cell(30, 5, _sanitize(classified[:20]), fill=True, border=0)

            # Response column
            pdf.cell(0, 5, _sanitize(inf.response[:95]), fill=True, border=0, ln=True)

        if len(items) > 10:
            pdf.set_text_color(*_GRAY)
            pdf.set_font("Helvetica", "I", 8)
            pdf.cell(0, 5, f"  ... and {len(items) - 10} more", ln=True)
        pdf.ln(4)

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(output_path))

    return output_path
